#!/bin/bash
# Variables — change the bucket name, must be globally unique
REGION="eu-central-1"
ACCOUNT_ID=$(aws --profile sofa sts get-caller-identity --query Account --output text)
BUCKET_NAME="gitops-platform-tfstate-${ACCOUNT_ID}"

# 1. Create S3 bucket
aws --profile sofa s3api create-bucket   --bucket $BUCKET_NAME   --region $REGION   --create-bucket-configuration LocationConstraint=$REGION

# 2. Enable versioning (lets you roll back state)
aws --profile sofa s3api put-bucket-versioning   --bucket $BUCKET_NAME   --versioning-configuration Status=Enabled

# 3. Block ALL public access (never public)
aws --profile sofa s3api put-public-access-block   --bucket $BUCKET_NAME   --public-access-block-configuration     "BlockPublicAcls=true,IgnorePublicAcls=true,     BlockPublicPolicy=true,RestrictPublicBuckets=true"

# 4. Enable encryption at rest
aws --profile sofa s3api put-bucket-encryption   --bucket $BUCKET_NAME   --server-side-encryption-configuration     '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'


echo "Bootstrap done. Bucket: $BUCKET_NAME"